default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: 

development:
  <<: *default
  database: api

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
