default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  # username: api
  username: mapa_eleitoral

development:
  <<: *default
  database: api

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
